default_path="../Resource/motion/"

-- 사용할 skeleton의 목록. BVH나 TRC의 경우 동작까지 로딩되지만, 일반적인 경우 MotionLoader::loadAnimation을 사용.
resource={
	{"hyunwoo_lowdof_T.wrl", "locomotion_hyunwoo/hyunwoo_lowdof_T.wrl", "locomotion_hyunwoo/hyunwoo_lowdof_T_locomotion_hl.dof"},
	{"gymnist.wrl", "gymnist/gymnist.wrl", "gymnist/gymnist.dof",initialHeight=0.07},
	{"justin_straight_run.wrl", "justin_straight_run/justin_straight_run.wrl","justin_straight_run/justin_straight_run.dof"},
	"dance/dance-cs-bvh.bvh",
	"dance/boa_number1.bvh",
	"dance/waltz_m.bvh",
	"dance/waltz_w.bvh",
	"dance/Dance_MW_01_M.bvh",
	"dance/Dance_MW_01_W.bvh",
	"dance/Dance_MW_02_M.bvh", 
	"dance/Dance_MW_02_W.bvh", 
	"dance/Dance_W_01.bvh",
	"dance/Dance_W_02.bvh", 
	"dance/k_wk2.bvh", 
	"dance/dg-306-d.bvh",
	"dance/dg-306-g.bvh",
	"take_8/man1.bvh",
	"take_8/man2.bvh",
	{"walker.vsk","Walking_Control_2/Project 1/Capture day 1/Session 1/walker.vsk"}, 
	"test_v/subject.vsk",
	"boxer/Boxer.ASF",
	"locomotion/onion/A_1_30F.bvh",
	"locomotion_hyunwoo/Run_01.bvh",
	"locomotion_hyunwoo/locomotion_hl.mot",
	"LOCOMOTION_HYUNWOO2/RUN_01.bvh",
	"LOCOMOTION_HYUNWOO2/locomotion.mot",
	"man1long.mot",
	"man2long.mot",
	"man1longus.mot",
	"man2longus.mot",
	"man1all.mot",
	"man2all.mot",
	"kickboxer/man1all_nd.mot",
	"kickboxer/man2all_nd.mot",
	"TWOCHARACTER/mana_01.bvh",
	-- MUAYTHAI
	{"muaythai1.skl", "kickboxer/muaythai/Fight_001_1_trim1_sm_A.bvh", "loadSkeletonOnly"},
	{"muaythai2.skl", "kickboxer/muaythai/Fight_001_1_trim1_sm_B.bvh", "loadSkeletonOnly"},
	{"muaythai1_com.skl", "kickboxer/muaythai/muaythai1_ndCOM.mot", "loadSkeletonOnly"},
	{"muaythai2_com.skl", "kickboxer/muaythai/muaythai2_ndCOM.mot", "loadSkeletonOnly"},
	"muaythai/muaythai1.mot",
	"muaythai/muaythai2.mot",
	{"test1.trc","trc/Day5_Session1_Take01_ddong_-_walk.trc", "USE_TRANSLATION_JOINT"},
	{"iguana.trc","trc/Day5_Session1_Take01_ddong_-_walk.trc", "USE_ROTATIONAL_JOINT"},
	{"iguana.skl", "trc/iguana_motion_set.mot", "loadSkeletonOnly"},
	"trc/iguana_from248.bvh",
	"wd2/wd2.asf"
}
