#ifndef _MY_H
#define _MY_H

enum NodeType_T
{ TRANSFORM , SHAPE, INDEXEDFACESET,
TIMESENSOR,ORIENTATIONIP,POSITIONIP,ROUTE,GENERAL,COORDINATEIP,COMBINEDTRANSFORM, SHAPECONTAINER, MATRIXIP, POSTUREIP, BONE } ;// 주의: 순서를 바꾸지 말것 추가는 뒤로 할것 (기존 버젼 파일과 호환성을 위해서)

#endif

