skel=MotionLoader(1)
bone=skel:GetBoneFromVoca("HIPS")
skel:printHierarchy()
skel:insertChildBone(bone, "hips2", true)
skel:insertJoint(skel:GetBoneFromName("hips2"), "RT")
curMot=currMotion()
curMot:init(skel)
print("hihi\n")
skel:printHierarchy()