walknn:
	python3 test_walk2.py gym_walkCDM/testWalkV2_FA.lua
pushnn:
	python3 test_walk2.py gym_walkCDM/testPush_FA.lua
install_dependencies:
	pip3 install torch python3-tk gym
example_ragdoll:
	python3 test_sample_python.py examples/RagdollFallLCP_selfContained.lua
example_ballfall:
	python3 test_sample_python.py examples/BallFall.lua
example_pendulum:
	python3 test_sample_python.py examples/BallFall2.lua
example_boxfall:
	python3 test_sample_python.py examples/BoxFall.lua
